#!/usr/bin/env bash
cd "${0%/*}" || exit 1
source /usr/lib/openfoam/openfoam2406/etc/bashrc
find . -maxdepth 1 -regextype posix-extended -regex './[0-9]+(\.[0-9]+)?' -exec rm -rf {} +
rm -rf 0 processor* log.* postProcessing
cp -r 0.orig 0
blockMesh > log.blockMesh 2>&1
viscoplasticAlgFoam > log.run 2>&1
echo done
tail -5 log.run
